// #include<iostream>
// using namespace std;

// int main(){
//     int n;
//     cin>>n;


//     if (n>0)
//     {
//         cout<<"Positive number";
//     }
//     else if (n<0)
//     {
//         cout<<"Negative number";
//     }
//     else
//     {
//         cout<<"Zero";
//     }
    
//     return 0;
// }

// --- IGNORE ---

#include<iostream>
using namespace std;

// int main(){
//     int a , b;

//     cout <<"Enter the value of a :"<<endl;
//     cin>>a;
//     cout<<"Enter the value of b :"<<endl;
//     cin>>b;

//     if (a>b)
//     {
//         cout<<"a is greater than b";
//     }
//     else if (b>a)
//     {
//         cout<<"b is greater than a";
//     }
//     else
//     {
//         cout<<"a is equal to b";
//     }
    
//     return 0;
// }


// --- IGNORE ---


// #include<iostream>
// using namespace std;

// int main(){
    
//     int a = 2;
//     int b = a+1;

//     if ((a=3)==b)
//     {
//        cout<<a;

//     }
//     else
//     {
//         cout<<a+1;
//     }
//     return 0;
// }

// #include<iostream>
// using namespace std;

// int main(){
//     int a = 24;

//     if (a>20)
//     {
//         cout<<"love";
//     }
//     else if (a==20)
//     {
//         cout<<"lovely";
//     }
//     else
//     {
//         cout<<"babar";
//     }
//     return 0;
// }

// #include<iostream>
// using namespace std;

// int main(){
//     char ch;
//     cout<<"Enter the a letter :"<<endl;
//     cin>>ch;

//     if (ch >= 'A' && ch <= 'Z')
//     {
//         cout<<"Uppercase letter";
//     }
//     else if (ch >= 'a' && ch <= 'z')
//     {
//         cout<<"Lowercase letter";
//     }
//     else
//     {
//         cout<<"Not an alphabet";
//     }
    
//     return 0;
// }

// #include<iostream> 
// using namespace std;

// int main(){
    
//     int n;
//     cin>>n;

//     int i = 1;
//     while (i<=n)
//     {
//         cout <<i<<" ";
//         i=i+1;
//     }
    
//     return 0;
// }

#include<iostream>
using namespace std;

int main(){
    
    return 0;
}